In [2]:
import numpy as np

In [8]:
# columns = [age, heart_rate, cholesterol, blood_pressure]
patients = np.array([
    [45, 80, 200, 120],
    [60, 90, 240, 140],
    [30, 70, 180, 110],
    [50, 85, 220, 130],
    [65, 95, 260, 150]
])

In [9]:
patients

array([[ 45,  80, 200, 120],
       [ 60,  90, 240, 140],
       [ 30,  70, 180, 110],
       [ 50,  85, 220, 130],
       [ 65,  95, 260, 150]])

In [10]:
patients.shape

(5, 4)

In [11]:
patients.shape[0]   #patients

5

In [12]:
patients.shape[1]  #features (columns)

4

In [13]:
patients[0]   #first patient

array([ 45,  80, 200, 120])

In [14]:
patients[:, 0]   #ages

array([45, 60, 30, 50, 65])

In [15]:
patients[:, 3]   # blood pressure 

array([120, 140, 110, 130, 150])

In [20]:
np.mean(patients[:, 0])   #average age

np.float64(50.0)

In [21]:
np.max(patients[:, 1])   #maximum heart rate

np.int64(95)

In [22]:
np.min(patients[:, 2])    #minimum cholesterol level

np.int64(180)

In [23]:
patients[patients[:, 3] > 130]  #blood pressure > 130

array([[ 60,  90, 240, 140],
       [ 65,  95, 260, 150]])

In [24]:
patients[patients[:, 2] >= 240]   # cholesterol ≥ 240

array([[ 60,  90, 240, 140],
       [ 65,  95, 260, 150]])

In [25]:
patients[patients[:, 0] > 50]   #older than 50

array([[ 60,  90, 240, 140],
       [ 65,  95, 260, 150]])

In [26]:
patients[(patients[:, 3] > 140) | (patients[:, 2] > 240)]  #high-risk patients


array([[ 65,  95, 260, 150]])

In [34]:
under50_avg = np.mean(patients[patients[:, 0] < 50][:, 1])
over50_avg = np.mean(patients[patients[:, 0] >= 50][:, 1])

print(under50_avg)
print(over50_avg)

75.0
90.0


In [40]:
patients[patients[:, 3] == max(patients[:, 3])]  #Highest blood pressure

array([[ 65,  95, 260, 150]])

In [41]:
patients[patients[:, 1] == min(patients[:, 1])]    #Lowest heart rate

array([[ 30,  70, 180, 110]])

In [47]:
print(patients[:, [0, 3]])   # age vs blood pressure

print("Older patients tend to have higher blood pressure (positive relationship in this dataset)")

[[ 45 120]
 [ 60 140]
 [ 30 110]
 [ 50 130]
 [ 65 150]]
Older patients tend to have higher blood pressure (positive relationship in this dataset)
