In [1]:
import numpy as np

In [2]:
pationt_ID = np.array([101, 102, 103, 104, 105])
heart_rates = np.array([72, 110, 95, 130, 88])


status = np.where(heart_rates>100, "critical", "stable")

print("pationt_ID: ", pationt_ID)
print("heart_rates: ", heart_rates)
print("status: ", status)

pationt_ID:  [101 102 103 104 105]
heart_rates:  [ 72 110  95 130  88]
status:  ['stable' 'critical' 'stable' 'critical' 'stable']


In [3]:
temp = np.array([36.5, 37.2, 0, 38.1, 0, 36.8])

condition = temp != 0

filtered = temp[condition]
print(filtered)
avg_temp = filtered.mean()
print(avg_temp)

cleaned_temp = np.where(temp == 0, avg_temp, temp)

print("original: ", temp)
print("clened: ", cleaned_temp)

[36.5 37.2 38.1 36.8]
37.150000000000006
original:  [36.5 37.2  0.  38.1  0.  36.8]
clened:  [36.5  37.2  37.15 38.1  37.15 36.8 ]


In [4]:
cleaned_temp[cleaned_temp[0:]> 37]

array([37.2 , 37.15, 38.1 , 37.15])

In [5]:
cond2 = cleaned_temp >37
cond2

array([False,  True,  True,  True,  True, False])

In [6]:
filterd = cleaned_temp[cond2]
filterd

array([37.2 , 37.15, 38.1 , 37.15])

In [7]:
ages = np.array([25, 65, 70, 50, 45])
bp = np.array([120, 150, 135, 160, 145])

risk = np.where((( ages > 70) | (bp > 130) ), "risk", "normal" )

print(risk)

['normal' 'risk' 'risk' 'risk' 'risk']


In [8]:
salaries = np.array([400, 600, 550, 300, 700])

bonus = np.where((salaries>=500), salaries+100 , salaries+50)

print(bonus)

[450 700 650 350 800]


In [9]:
marks = np.array([90, 75, 60, 82, 68])

grades = np.where(marks>= 85, "A", np.where(marks>=70, "B", "C"))

print(grades)

['A' 'B' 'C' 'B' 'C']


In [10]:
marks = np.array([99, 75, 60, 82, 68, 89])

grades = np.where(marks>= 85, np.where(marks>= 95, "A+","A"), np.where(marks>=70, "B", "C"))

print(grades)

['A+' 'B' 'C' 'B' 'C' 'A']


In [11]:
purchases = np.array([50, 120, 80, 200, 150])

dis = np.where(purchases>100 , purchases*0.8, purchases*0.9)

print(dis)

[ 45.  96.  72. 160. 120.]


In [12]:
hert_rate = np.array([80, 130, 110, 140, 90])
bp = np.array([120, 150, 135, 160, 145])

risk = np.where((( hert_rate > 70) & (bp > 130) ), "risk", "normal" )

print(risk)

['normal' 'risk' 'risk' 'risk' 'risk']


In [13]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
np.linspace(0, 1, 5, endpoint=False)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [15]:
np.linspace(10, 0, 5)

array([10. ,  7.5,  5. ,  2.5,  0. ])

In [16]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [17]:
import pandas as pd

In [19]:
data = [1, 3, 4, 5, 6]
series = pd.Series(data)
print(series)

0    1
1    3
2    4
3    5
4    6
dtype: int64


In [21]:
s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])

s.index.name = 'My_index'


In [22]:
s

My_index
a    10
b    20
c    30
dtype: int64

In [34]:
s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])

s.index = [1,2,3]
s.index.name = 'My_index'


In [43]:
s

My_index
1    10
2    20
3    30
dtype: int64

In [44]:
s.values

array([10, 20, 30])

In [45]:
max(s.values)

np.int64(30)

In [46]:
import numpy as np

avg = np.mean(s.values)
print(avg)

20.0


In [47]:
s.index

Index([1, 2, 3], dtype='int64', name='My_index')

In [50]:
s.name = "Final_scores"
print(f"Updated name: {s.name}")

Updated name: Final_scores


In [51]:
s

My_index
1    10
2    20
3    30
Name: Final_scores, dtype: int64

In [52]:
s[1]

np.int64(10)

In [53]:
s[2]

np.int64(20)

In [54]:
s[s>20]

My_index
3    30
Name: Final_scores, dtype: int64

In [55]:
s[s<10]

Series([], Name: Final_scores, dtype: int64)

In [56]:
s[s>=30]

My_index
3    30
Name: Final_scores, dtype: int64

In [62]:
if 2 in s:
    print(True)

True


In [63]:
2 in s

True

In [65]:
dic = s.to_dict()
dic

{1: 10, 2: 20, 3: 30}

In [72]:
s1=pd.Series(dic)
s1

1    10
2    20
3    30
dtype: int64

In [73]:
countriesPop = pd.Series([
8700000,
4300000,
3000000,
2100000],
index = ['China','Germany','Japan','USA'])
countriesPop.name = "countriesPop"

In [74]:
pd.isnull(countriesPop)

China      False
Germany    False
Japan      False
USA        False
Name: countriesPop, dtype: bool

In [75]:
pd.notnull(countriesPop)

China      True
Germany    True
Japan      True
USA        True
Name: countriesPop, dtype: bool

In [76]:
countriesPop = pd.Series([
8700000,
4300000,
3000000,
2100000,
np.nan],
index = ['China','Germany','Japan','USA','Oman'])
countriesPop.name = "countriesPop"

In [77]:
pd.isnull(countriesPop)

China      False
Germany    False
Japan      False
USA        False
Oman        True
Name: countriesPop, dtype: bool

In [78]:
pd.notnull(countriesPop)

China       True
Germany     True
Japan       True
USA         True
Oman       False
Name: countriesPop, dtype: bool

In [79]:
pd.isnull(countriesPop).sum()

np.int64(1)

In [80]:
pd.notnull(countriesPop).sum()

np.int64(4)

In [83]:
countriesPop2 = pd.Series([
8700000,
4300000,
3000000,
2100000,
5000000],
index = ['China','Germany','Japan','USA','Oman'])
countriesPop2.name = "countriesPop"

In [85]:
countriesPop + countriesPop2

China      17400000.0
Germany     8600000.0
Japan       6000000.0
USA         4200000.0
Oman              NaN
Name: countriesPop, dtype: float64

In [88]:
s = pd.Series({'m':85, 'sin':90, 'E':78})

print(s[s > 80])

m      85
sin    90
dtype: int64


In [89]:
s = pd.Series([10, None, 30, None, 50])

print("Missing values: ", s.isna().sum())

mean_val = s.mean()
print("Filled Seriese: ")
print(s.fillna(mean_val))

Missing values:  2
Filled Seriese: 
0    10.0
1    30.0
2    30.0
3    30.0
4    50.0
dtype: float64


In [95]:
names = pd.Series(["Mohammed","khlifa", "Ahmed", "Omar","Aziz"])

print(names.str.upper())

print(names[names.str.len() > 5])
print("\n")

0    MOHAMMED
1      KHLIFA
2       AHMED
3        OMAR
4        AZIZ
dtype: str
0    Mohammed
1      khlifa
dtype: str




In [98]:
s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])

s.rename(index = {"a" : "X"}, inplace = True)
print(s)

s["y"] = 40
print(s)

X    10
b    20
c    30
dtype: int64
X    10
b    20
c    30
y    40
dtype: int64


In [99]:
s = pd.Series([50, 60, 30,40,10])

print(s.sort_values())


4    10
2    30
3    40
0    50
1    60
dtype: int64


In [100]:
s = pd.Series([50, 60, 30,40,10])

print(s.sort_index())

0    50
1    60
2    30
3    40
4    10
dtype: int64


In [101]:
s = pd.Series(["A", "B", "A","C","A", "B"])

print(s.value_counts())

A    3
B    2
C    1
Name: count, dtype: int64


In [103]:
s1 = pd.Series([10, 20, 30])
s2 = pd.Series([15, 15, 35])

print("s1 > s2")
print(s1 > s2)

print("s1 == s2")
print(s1 == s2)


s1 > s2
0    False
1     True
2    False
dtype: bool
s1 == s2
0    False
1    False
2    False
dtype: bool


In [104]:
sales = pd.Series([200, 450, 300, 150, 500],  index=["Mon", "Tue", "Wed", "Thu", "Fri"])

# Total sales
print("Total:", sales.sum())

# Average sales
print("Average:", sales.mean())

# Max sales day
print("Highest day:", sales.idxmax())

# Sales > 300
print("Days with sales > 300:")
print(sales[sales > 300])


Total: 1600
Average: 320.0
Highest day: Fri
Days with sales > 300:
Tue    450
Fri    500
dtype: int64


In [106]:
data = {
'Name': ['Alice', 'Bob', 'Charlie'],
'Age': [24, 27, 22],
'City': ['New York', 'Los Angeles', 'Chicago']
}

df = pd.DataFrame(data)
df

,Name,Age,City
0,Alice,24,New York
1,Bob,27,Los Angeles
2,Charlie,22,Chicago


In [107]:
df.head(2)

,Name,Age,City
0,Alice,24,New York
1,Bob,27,Los Angeles


In [108]:
df.tail(1)

,Name,Age,City
2,Charlie,22,Chicago


In [113]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str  
 1   Age     3 non-null      int64
 2   City    3 non-null      str  
dtypes: int64(1), str(2)
memory usage: 204.0 bytes
None


In [114]:
print(df.describe())

             Age
count   3.000000
mean   24.333333
std     2.516611
min    22.000000
25%    23.000000
50%    24.000000
75%    25.500000
max    27.000000


In [116]:
print(df['Name'])



0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str


In [117]:
print(df[['Name', 'City']])

      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago


In [118]:
print(df["Age"].mean())

24.333333333333332


In [119]:
print(df.iloc[0])

Name       Alice
Age           24
City    New York
Name: 0, dtype: object


In [125]:
print(df.loc[1])

Name            Bob
Age              27
City    Los Angeles
Name: 1, dtype: object


In [127]:
pip install Kagglehub

Note: you may need to restart the kernel to use updated packages.


In [8]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "data_science_student_marks.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "sudhirsingh108/data-science-students",
  file_path,
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records: ")
df.head()

C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\DELL\AppData\Local\Temp\ipykernel_31092\2909647910.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(


First 5 records: 


,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,Sydney,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82
2,6,Berlin,22,72,70,99,79,77
3,7,London,23,97,90,74,72,85
4,8,Tokyo,22,91,71,79,80,75


In [5]:
import numpy as np

In [6]:
import pandas as pd


In [9]:
df.info

<bound method DataFrame.info of      student_id     location  age  sql_marks  excel_marks  python_marks  \
0             4       Sydney   24         95           99            87   
1             5        Tokyo   24         99           95            89   
2             6       Berlin   22         72           70            99   
3             7       London   23         97           90            74   
4             8        Tokyo   22         91           71            79   
..          ...          ...  ...        ...          ...           ...   
492         496     New York   23         71           92            98   
493         497  Los Angeles   20         90          100            90   
494         498        Paris   22         78           80            78   
495         499  Los Angeles   21         96           93            78   
496         500       London   22         85           87            93   

     power_bi_marks  english_marks  
0                82           

In [10]:
df["location"]

0           Sydney
1            Tokyo
2           Berlin
3           London
4            Tokyo
          ...     
492       New York
493    Los Angeles
494          Paris
495    Los Angeles
496         London
Name: location, Length: 497, dtype: str

In [11]:
df["location"].unique()

<StringArray>
[     'Sydney',       'Tokyo',      'Berlin',      'London',     'Toronto',
   'Melbourne',       'Paris', 'Los Angeles',    'New York']
Length: 9, dtype: str

In [12]:
df["location"].value_counts()

location
Tokyo          60
Los Angeles    60
Melbourne      58
New York       57
Toronto        56
Paris          55
Sydney         53
Berlin         52
London         46
Name: count, dtype: int64

In [13]:
df["sql_marks"].mean()

np.float64(84.66197183098592)