In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [5]:
arr = np.array(
    [1,2,3,4]
)

In [6]:
arr

array([1, 2, 3, 4])

In [8]:
arr_2d = np.array([[1,2,3,4] , [5,6,7,8]])

In [9]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
lis1 = [12, 30, 10]

myArra = np.array(lis1)

In [11]:
myArra

array([12, 30, 10])

In [15]:
lis2D = [
    [12,30,20],
    [22,33,44]
]
my2DArra = np.array(lis2D)

In [16]:
my2DArra

array([[12, 30, 20],
       [22, 33, 44]])

In [17]:
my2DArra.shape

(2, 3)

In [20]:
my2DArra.shape[0] #rows number

2

In [21]:
my2DArra.shape[1] #coulme number

3

In [22]:
my2DArra.dtype

dtype('int64')

In [23]:
np.zeros(3, 'int')

array([0, 0, 0])

In [24]:
np.ones(3, 'int')

array([1, 1, 1])

In [25]:
np.ones(3)

array([1., 1., 1.])

In [26]:
np.ones([5,5], 'int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [27]:
np.empty(3)

array([1., 1., 1.])

In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(0, 50, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [32]:
arr1= np.array([[1,2,3,4], [5,6,7,8]])

In [33]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
arr1*arr1

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [35]:
arr1-2

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6]])

In [40]:
arr2= np.array([[10,20,30,40], [50,60,70,80]])

In [42]:
arr1*arr2

array([[ 100,  400,  900, 1600],
       [2500, 3600, 4900, 6400]])

In [43]:
arr1*2

array([[ 20,  40,  60,  80],
       [100, 120, 140, 160]])

In [44]:
arr1**2

array([[ 100,  400,  900, 1600],
       [2500, 3600, 4900, 6400]])

In [45]:
arr1

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [46]:
arr1.T

array([[10, 50],
       [20, 60],
       [30, 70],
       [40, 80]])

In [48]:
 # Taking dot product of matrices
A=np.array([[1,2,3],[4,5,6]])
print(A)
print('\n')
B=np.array([[7,8],[9,10],[11,12]])
print(B)
print('\n')
np.dot(A,B)

[[1 2 3]
 [4 5 6]]


[[ 7  8]
 [ 9 10]
 [11 12]]




array([[ 58,  64],
       [139, 154]])

In [50]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
lastElement= arr[arr.shape[0]-1]
lastElement

np.int64(10)

In [52]:
print(lastElement)

10


In [53]:
arr[4:8]

array([4, 5, 6, 7])

In [54]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [55]:
A=np.array([[1,2,3],[4,5,6]])
A[ :2, 2:]

array([[3],
       [6]])

In [56]:
A=np.array([[1,2,3],[4,5,6]])
A[ :2, :2]


array([[1, 2],
       [4, 5]])

In [57]:
A=np.array([[1,2,3],[4,5,6]])
A[ 2:2, 2:2]

array([], shape=(0, 0), dtype=int64)

In [58]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
arr=np.arange(0,11)
arr

NameError: name 'np' is not defined

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [7]:
A=np.array([[1,2,3],[4,5,6]])

A[1,2]=99

In [8]:
A

array([[ 1,  2,  3],
       [ 4,  5, 99]])

In [9]:
A[1]

array([ 4,  5, 99])

In [10]:
A[: , 1]

array([2, 5])

In [11]:
A[1][2]

np.int64(99)

In [12]:
A[:3, ::2]

array([[ 1,  3],
       [ 4, 99]])

In [13]:
newarr= np.arange(1,13)
newarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
reshapedArr = newarr.reshape(4,3)
reshapedArr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
x = np.array([1,2,3])
y = np.array([3,2,1])

result= np.concatenate([x,y])
result

array([1, 2, 3, 3, 2, 1])

In [28]:
arr2DA = result.reshape(2,3)
arr2DB = result.reshape(2,3)


In [29]:
arr2DA


array([[1, 2, 3],
       [3, 2, 1]])

In [30]:

arr2DB

array([[1, 2, 3],
       [3, 2, 1]])

In [31]:
result= np.concatenate([arr2DA,arr2DB])
result

array([[1, 2, 3],
       [3, 2, 1],
       [1, 2, 3],
       [3, 2, 1]])

In [32]:
result= np.concatenate([arr2DA,arr2DB], axis=0)
result

array([[1, 2, 3],
       [3, 2, 1],
       [1, 2, 3],
       [3, 2, 1]])

In [33]:
result= np.concatenate([arr2DA,arr2DB], axis=1)
result

array([[1, 2, 3, 1, 2, 3],
       [3, 2, 1, 3, 2, 1]])

In [35]:
grid = np.arange(16).reshape(4, 4)
print(grid)
print("\n")
upper,lower=np.vsplit(grid, [2])
print(upper)
print("\n")
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[[0 1 2 3]
 [4 5 6 7]]


[[ 8  9 10 11]
 [12 13 14 15]]


In [37]:
grid = np.arange(16).reshape(4, 4)
print(grid)
print("\n")
left,right=np.hsplit(grid, [1])
print(left)
print("\n")
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[[ 0]
 [ 4]
 [ 8]
 [12]]


[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [38]:
left.shape

(4, 1)

In [39]:
right.shape

(4, 3)

In [40]:
grid = np.arange(1,17).reshape(4, 4)
print(grid)
print("\n")
a, b =np.hsplit(grid, [3])
print(a)
print("\n")
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


[[ 4]
 [ 8]
 [12]
 [16]]


In [41]:
grid = np.arange(20).reshape(4, 5)
print(grid)
print("\n")
a, b =np.hsplit(grid, [2])
print(a)
print("\n")
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]]


[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [42]:
grid = np.arange(20).reshape(4, 5)
print(grid)
print("\n")
a, b, c =np.hsplit(grid, [2,4])
print(a)
print("\n")
print(b)
print("\n")
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]]


[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]


[[ 4]
 [ 9]
 [14]
 [19]]


In [43]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [45]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [46]:
A = np.random.randn(10)
A

array([-0.10311775, -1.66204338,  0.32899091, -0.26698742, -0.66753956,
       -0.54322117, -2.15334852,  0.19265413,  0.37487112,  1.19242744])

In [47]:
A = np.random.randint(5,100,20)
B = np.random.randint(5,100,20)
print(A)
print(B)

[68  8 18 38 30 57 68 38 33 62 62 19 80 33 31  6 78 36 37 39]
[ 5 24 30 86 40 61 73 66 36 64 97 14 21 81 10 62 87 30 50 31]


In [48]:
np.add(A,B)

array([ 73,  32,  48, 124,  70, 118, 141, 104,  69, 126, 159,  33, 101,
       114,  41,  68, 165,  66,  87,  70], dtype=int32)

In [49]:
np.maximum(A,B)

array([68, 24, 30, 86, 40, 61, 73, 66, 36, 64, 97, 19, 80, 81, 31, 62, 87,
       36, 50, 39], dtype=int32)

In [51]:
np.minimum(A,B)

array([ 5,  8, 18, 38, 30, 57, 68, 38, 33, 62, 62, 14, 21, 33, 10,  6, 78,
       30, 37, 31], dtype=int32)

In [52]:
A= np.array([1,2,3,4])
B= np.array([100,200,300,400])

condation = np.array([True,True,False,False])
c= np.where(condation,A,B)
c

array([  1,   2, 300, 400])

In [59]:
A= np.array([1,2,3,4])
B= np.array([100,200,300,400])

condation = np.array([True,True,False,False])
c= np.where(condation,A,B)
c

array([  1,   2, 300, 400])

In [62]:
c2D=c.reshape(2,2)
c2D

array([[  1,   2],
       [300, 400]])

In [64]:
arr= np.random.randn(5,5)
arr

array([[-0.61409878, -0.09629537, -0.06913389,  1.05682444, -0.15935751],
       [-1.14398486,  0.00647436,  0.45555971,  0.68072381,  0.29802532],
       [-1.16953431, -1.02596665,  0.74049883, -1.89352955, -0.58573537],
       [ 0.51152553, -1.55050658,  0.44246658,  0.2832841 , -0.7750418 ],
       [-0.34896043, -1.0199983 , -0.42791293, -0.02163351,  1.34042307]])

In [67]:
np.where(arr < 0, 0, arr)

array([[0.        , 0.        , 0.        , 1.05682444, 0.        ],
       [0.        , 0.00647436, 0.45555971, 0.68072381, 0.29802532],
       [0.        , 0.        , 0.74049883, 0.        , 0.        ],
       [0.51152553, 0.        , 0.44246658, 0.2832841 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 1.34042307]])

In [68]:
np.where(arr < 0, True, arr)

array([[1.        , 1.        , 1.        , 1.05682444, 1.        ],
       [1.        , 0.00647436, 0.45555971, 0.68072381, 0.29802532],
       [1.        , 1.        , 0.74049883, 1.        , 1.        ],
       [0.51152553, 1.        , 0.44246658, 0.2832841 , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.34042307]])

In [70]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
arr.sum()

np.int64(45)

In [73]:
print(arr.sum(1))

[ 6 15 24]


In [74]:
print(arr.sum(0))

[12 15 18]


In [76]:
arr.mean()

np.float64(5.0)

In [77]:
arr.std()

np.float64(2.581988897471611)

In [79]:
arr.var() #variance

np.float64(6.666666666666667)

In [81]:
bool_arr = np.array([False, False, False])
bool_arr.any()

np.False_

In [82]:
bool_arr = np.array([True, False, False])
bool_arr.any()

np.True_

In [86]:
bool_arr = np.array([True, False, False])
bool_arr.all()

np.False_

In [87]:
bool_arr = np.array([True, True, True])
bool_arr.all()

np.True_

In [88]:
A = np.array([-2, 5, 4, -8, 0])
print(A)

[-2  5  4 -8  0]


In [90]:
print(np.sort(A))
print(-np.sort(A))

[-8 -2  0  4  5]
[ 8  2  0 -4 -5]
